name: Trigger the 'playwright-github' Test Workflow on Testkube

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: kubeshop/setup-testkube@v1
        with:
          organization: tkcorg_5664f361950f1603
          environment: tkcenv_538e98c4494bc7ad
          token: ${{ secrets.TK_API_TOKEN }}
          url: "http://localhost:8081/organization/demo/environment/my-first-environment/dashboard/test-workflows/cypress-github/"
